# Generated by Django 2.0.5 on 2019-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_l', models.CharField(max_length=10, verbose_name='業態カテゴリ')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=6, verbose_name='都道府県')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
