# Generated by Django 2.1.5 on 2019-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_remove_review_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='画像１URL'),
        ),
    ]
